---
istio_traffic_policies_work_dir: "/etc/kubernetes/istio-traffic-policies"

istio_traffic_policies:
  - name: decision-flow-web
    namespace: prod-paas-components
    host: decision-flow-web.prod-paas-components.svc.cluster.local
    port: 80

    subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2

    canary:
      enabled: true
      gatewayHost: decision.itexcloud.com
      gatewayRef: istio-ingress-public/public-gateway
      weights:
        - subset: v1
          weight: 90
        - subset: v2
          weight: 10

    resilience:
      enabled: true
      timeout: 3s
      retries:
        attempts: 3
        perTryTimeout: 1s
        retryOn: 5xx,connect-failure,refused-stream

      connectionPool:
        tcpMaxConnections: 100
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10

      outlierDetection:
        consecutive5xxErrors: 5
        interval: 10s
        baseEjectionTime: 30s
        maxEjectionPercent: 50
