apiVersion: apps/v1
kind: Deployment
metadata:
  name: klinx-imes-server-v1
  namespace: saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klinx-imes-server
      version: v1
  template:
    metadata:
      labels:
        app: klinx-imes-server
        version: v1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 20
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 20
      terminationGracePeriodSeconds: 5
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - klinx-imes-server
                topologyKey: kubernetes.io/hostname
      containers:
        - name: klinx-imes-server
          imagePullPolicy: Always
          image: node5:443/itex-biz/klinx-imes-server:private_jingyuan_qa_sit
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: saas-config
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 6144Mi
          ports:
            - name: tcp-8736
              containerPort: 8736
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8736
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 6
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8736
              scheme: HTTP
            initialDelaySeconds: 6
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8736
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 6
            successThreshold: 1
            failureThreshold: 30
      dnsPolicy: ClusterFirst