- name: Create directories
  ansible.builtin.file:
    path: "{{ dir_base }}/{{ item.0 }}/{{ item.1 }}"
    state: directory
    mode: "0755"
  loop: "{{ dir_envs | product(dir_components.keys()) | list }}"

- name: Set ownership for directories
  ansible.builtin.file:
    path: "{{ dir_base }}/{{ item.0 }}/{{ item.1 }}"
    owner: "{{ dir_components[item.1] }}"
    group: "{{ dir_components[item.1] }}"
    recurse: true
  loop: "{{ dir_envs | product(dir_components.keys()) | list }}"

- name: Find directories
  ansible.builtin.find:
    paths: "{{ dir_base }}"
    file_type: directory
  register: found_dirs

- name: Print directories
  ansible.builtin.debug:
    msg: "{{ found_dirs.files | map(attribute='path') | list }}"
