apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vminsert-pdb
  namespace: prod-distributed
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vminsert
      app.kubernetes.io/part-of: victoriametrics
