apiVersion: v1
kind: Service
metadata:
  name: vmstorage-headless
  namespace: prod-distributed
  labels:
    app.kubernetes.io/name: vmstorage
    app.kubernetes.io/part-of: victoriametrics
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: vmstorage
    app.kubernetes.io/part-of: victoriametrics
  ports:
    - name: http
      port: 8482
      targetPort: 8482
    - name: vminsert
      port: 8400
      targetPort: 8400
    - name: vmselect
      port: 8401
      targetPort: 8401
