apiVersion: v1
kind: Service
metadata:
  name: vmstorage
  namespace: prod-distributed
  labels:
    app.kubernetes.io/name: vmstorage
    app.kubernetes.io/part-of: victoriametrics
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: vmstorage
    app.kubernetes.io/part-of: victoriametrics
  ports:
    - name: http
      port: 8482
      targetPort: 8482
