apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq-prod
  namespace: prod-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rabbitmq-nfs-prod
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-rabbitmq-prod