apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: prod-basic
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "CHANGE_ME_RABBITMQ_DEFAULT_USER"
  RABBITMQ_DEFAULT_PASS: "CHANGE_ME_RABBITMQ_DEFAULT_PASS"