apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heapdump-pvc
  namespace: saas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: heapdump-nfs
  volumeName: heapdump-pv