apiVersion: apps/v1
kind: Deployment
metadata:
  name: klinx-datacollect-server
  namespace: saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klinx-datacollect-server
  template:
    metadata:
      labels:
        app: klinx-datacollect-server
    spec:
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 20
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 20
      terminationGracePeriodSeconds: 5
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - klinx-datacollect-server
                topologyKey: kubernetes.io/hostname
      containers:
        - name: klinx-datacollect-server
          imagePullPolicy: Always
          image: node5:443/itex-biz/klinx-datacollect-server:private_jingyuan_qa_sit
          envFrom:
            - configMapRef:
                name: saas-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 4096Mi
          ports:
            - name: tcp-8702
              containerPort: 8702
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8702
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 6
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8702
              scheme: HTTP
            initialDelaySeconds: 6
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8702
              scheme: HTTP
            initialDelaySeconds: 6
            timeoutSeconds: 1
            periodSeconds: 6
            successThreshold: 1
            failureThreshold: 20
      initContainers:
        - name: init
          image: busybox:1.36
          command:
            - sh
          args:
            - '-c'
            - until nc -vz klinx-idevicehub-server 8710;do echo waiting for base;sleep 2;done
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "25%"
      maxSurge: "25%"
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: klinx-datacollect-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-datacollect-server
  ports:
    - name: tcp-8702
      port: 8702
      protocol: TCP
      targetPort: 8702