apiVersion: apps/v1
kind: Deployment
metadata:
  name: klinx-iaps-server
  namespace: saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klinx-iaps-server
  template:
    metadata:
      labels:
        app: klinx-iaps-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - klinx-iaps-servers
                topologyKey: kubernetes.io/hostname
      containers:
        - name: klinx-iaps-server
          imagePullPolicy: Always
          image: node5:443/itex-biz/klinx-iaps-server:private_jingyuan_qa_sit
          env:
            - name: DISCOVERY_PORT
              value: "8713"               # 提供给 ${DISCOVERY_PORT}
            - name: SERVER_PORT
              value: "8713"               # 如果配置里用了 ${server.port}
          envFrom:
            - configMapRef:
                name: saas-config
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 3072Mi
          ports:
            - name: tcp-8713
              containerPort: 8713
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8713
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 6
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8713
              scheme: HTTP
            initialDelaySeconds: 6
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8713
              scheme: HTTP
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 6
            failureThreshold: 30
            periodSeconds: 10
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  name: klinx-iaps-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-iaps-server
  ports:
    - name: tcp-8713
      port: 8713
      protocol: TCP
      targetPort: 8713
      #nodePort: 32543
