apiVersion: apps/v1
kind: Deployment
metadata:
  name: klinx-datahub-server
  namespace: saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klinx-datahub-server
  template:
    metadata:
      labels:
        app: klinx-datahub-server
    spec:
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
      terminationGracePeriodSeconds: 5
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - klinx-datahub-server
                topologyKey: kubernetes.io/hostname
      containers:
        - name: klinx-datahub-server
          image: node5:443/itex-biz/klinx-datahub:private_hanew
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: saas-config
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 800m
              memory: 1800Mi
          ports:
            - name: tcp-9560
              containerPort: 9560
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9560
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 6
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9560
              scheme: HTTP
            initialDelaySeconds: 6
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9560
              scheme: HTTP
            initialDelaySeconds: 6
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: klinx-datahub-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-datahub-server
  ports:
    - name: tcp-9560
      port: 9560
      protocol: TCP
      targetPort: 9560