apiVersion: apps/v1
kind: Deployment
metadata:
  name: klinx-itpm-server
  namespace: saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klinx-itpm-server
  template:
    metadata:
      labels:
        app: klinx-itpm-server
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: klinx-itpm-server
          imagePullPolicy: Always
          image: node5:443/itex-biz/klinx-itpm-server:private_jingyuan_qa_sit
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: saas-config
          env:
            - name: DISCOVERY_PORT
              value: "8716"               # 提供给 ${DISCOVERY_PORT}
            - name: SERVER_PORT
              value: "8716"               # 如果配置里用了 ${server.port}
          resources:
            requests:
              cpu: 300m
              memory: 800Mi
            limits:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: root-logs
              mountPath: /root/logs
            - name: app-logs
              mountPath: /Users/texpro/data/projects/logs/klinx-itpm-server
            - name: heapdump
              mountPath: /heapdump
          ports:
            - name: tcp-8716
              containerPort: 8716
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8716
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 6
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8716
              scheme: HTTP
            initialDelaySeconds: 6
            periodSeconds: 2
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8716
              scheme: HTTP
            initialDelaySeconds: 6
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: tmp
          emptyDir: { }
        - name: root-logs
          emptyDir: { }
        - name: app-logs
          emptyDir: { }
        - name: heapdump
          persistentVolumeClaim:
            claimName: heapdump-pvc      
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: klinx-itpm-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-itpm-server
  ports:
    - name: tcp-8716
      port: 8716
      protocol: TCP
      targetPort: 8716
      #nodePort: 32543
