apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: prod-basic
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "CHANGE_ME_MONGODB_ROOT_USERNAME"
  MONGO_INITDB_ROOT_PASSWORD: "CHANGE_ME_MONGODB_ROOT_PASSWORD"