apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb-prod
  namespace: prod-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-nfs-static
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-mongodb-prod