apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: prod-distributed
type: Opaque
stringData:
  MINIO_ROOT_USER: "CHANGE_ME_MINIO_ROOT_USER"
  MINIO_ROOT_PASSWORD: "CHANGE_ME_MINIO_ROOT_PASSWORD"
