apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-prod
  namespace: prod-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-nfs-prod
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-redis-prod