---
# =========================
# kube-vip image
# =========================

kube_vip_image: "ghcr.io/kube-vip/kube-vip"
kube_vip_version: "v1.0.4"

# =========================
# Control-plane VIP
# =========================

kube_vip_address: "{{ kubevip_api_ip }}"
kube_vip_dns_name: "{{ kubevip_api_name | default('kubevip-api') }}"
kube_vip_port: 6443
kube_vip_subnet: 32

# 你也可以在 inventory/group_vars 里显式设置，比如 eth0
# 不设置时，task 会自动从 ansible_default_ipv4.interface 获取
kube_vip_interface: ""

# =========================
# Mode
# 阿里云 HAVIP/VPC 环境先用 ARP。
# 如果云厂商 HAVIP 机制要求 keepalived/arp 通知，则后续再针对云厂商微调。
# =========================

kube_vip_arp: true
kube_vip_leader_election: true

# 这个 role 只负责 control-plane VIP
kube_vip_cp_enable: true
kube_vip_svc_enable: false
kube_vip_lb_enable: false

# =========================
# Leader election
# =========================

kube_vip_lease_name_cp: "plndr-cp-lock"
kube_vip_lease_duration: 5
kube_vip_renew_deadline: 3
kube_vip_retry_period: 1

# =========================
# Metrics
# =========================

kube_vip_metrics_bind: ":2112"

# =========================
# Kubelet restart
# 通常不需要，kubelet 会自动 watch static pod manifest
# =========================

kube_vip_restart_kubelet: false