k8s_version: "1.34.2"
image_repo: "registry.cn-hangzhou.aliyuncs.com/google_containers"
pause_image: "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9"

# kubeadm.yaml / Calico 的网段
pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"

# kube-proxy / kubelet
kubeproxy_mode: "nftables"
cgroup_driver: "systemd"

#system_update的控制台兼master1
system_update_control_host: master1


# kube-vip
kube_vip_address: "172.16.15.60"
kube_vip_interface: "ens3"
kube_vip_port: 6443

# kubeadm HA endpoint
control_plane_endpoint: "172.16.15.60:6443"