apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: klinx-iwms-server
  namespace: saas
spec:
  hosts:
    - klinx-iwms-server
  http:
    - route:
        - destination:
            host: klinx-iwms-server
            subset: v1
          weight: 95
        - destination:
            host: klinx-iwms-server
            subset: v2
          weight: 5