apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio-dev
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-nfs-dev
  mountOptions:
    - vers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 172.16.15.66
    path: /data/jiyan/dev/minio