apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  namespace: dev-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-nfs-static
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-redis