apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-dev
  namespace: dev-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-nfs-dev
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-redis-dev