apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-dev
  namespace: dev-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-nfs-dev
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-mysql-dev