---
alloy_namespace: "logging"

alloy_chart_archive: "alloy-1.8.1.tgz"
alloy_work_dir: "/etc/kubernetes/alloy"

# Loki push endpoint
alloy_loki_push_url: "http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push"

# 多集群建议使用集群名作为 label
alloy_cluster_name: "prod-hz-01"

# 采集哪些 namespace 的 Pod 日志
alloy_log_namespaces:
  - kube-system
  - devops
  - monitoring
  - logging
  - prod-itex-components
  - prod-itex-servers
  - prod-paas-components
  - prod-srm-components
  - stable-itex-components
  - stable-itex-servers

# DaemonSet 模式下，每个 Alloy 只采当前节点上的 Pod 日志
alloy_keep_current_node_only: true

# 资源
alloy_cpu_request: "100m"
alloy_memory_request: "128Mi"
alloy_cpu_limit: "1000m"
alloy_memory_limit: "1Gi"

# Helm
alloy_helm_timeout: "10m"
