- name: Add docker-ce repo (Aliyun)
  command: dnf config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Copy crictl package to nodes
  copy:
    src: crictl-v1.34.0-linux-amd64.tar.gz
    dest: /tmp/crictl.tar.gz
    mode: "0644"

- name: Extract crictl
  unarchive:
    src: /tmp/crictl.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Ensure crictl is executable
  file:
    path: /usr/local/bin/crictl
    mode: "0755"

- name: Verify crictl
  command: /usr/local/bin/crictl version
  register: crictl_check
  changed_when: false

- name: Install containerd
  dnf:
    name: containerd
    state: present

- name: Ensure containerd dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/containerd
    - /etc/containerd/conf.d

- name: Deploy containerd config.toml
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: "0644"
  notify: Restart containerd

- name: Create certs.d directories
  file:
    path: "/etc/containerd/certs.d/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - docker.io
    - registry.k8s.io
    - gcr.io
    - ghcr.io
    - quay.io

- name: Configure docker.io registry mirrors
  copy:
    dest: /etc/containerd/certs.d/docker.io/hosts.toml
    mode: "0644"
    content: |
      server = "https://docker.io"

      [host."https://docker.m.daocloud.io"]
        capabilities = ["pull", "resolve"]

      [host."https://ccr.ccs.tencentyun.com"]
        capabilities = ["pull", "resolve"]

      [host."https://docker.1ms.run"]
        capabilities = ["pull", "resolve"]

      [host."https://dhub.kubesre.xyz"]
        capabilities = ["pull", "resolve"]

      [host."https://docker.kejilion.pro"]
        capabilities = ["pull", "resolve"]

      [host."https://docker.xuanyuan.me"]
        capabilities = ["pull", "resolve"]

      [host."https://docker.hlmirror.com"]
        capabilities = ["pull", "resolve"]

      [host."https://docker.melikeme.cn"]
        capabilities = ["pull", "resolve"]
  notify: Restart containerd


- name: Configure registry.k8s.io mirrors
  copy:
    dest: /etc/containerd/certs.d/registry.k8s.io/hosts.toml
    mode: "0644"
    content: |
      server = "https://registry.k8s.io"

      [host."https://docker.m.daocloud.io"]
        capabilities = ["pull", "resolve"]

      [host."https://ccr.ccs.tencentyun.com"]
        capabilities = ["pull", "resolve"]

      [host."https://docker.1ms.run"]
        capabilities = ["pull", "resolve"]

      [host."https://dhub.kubesre.xyz"]
        capabilities = ["pull", "resolve"]

      [host."https://docker.kejilion.pro"]
        capabilities = ["pull", "resolve"]

      [host."https://docker.xuanyuan.me"]
        capabilities = ["pull", "resolve"]

      [host."https://docker.hlmirror.com"]
        capabilities = ["pull", "resolve"]

      [host."https://docker.melikeme.cn"]
        capabilities = ["pull", "resolve"]
  notify: Restart containerd


- name: Configure gcr.io mirror
  copy:
    dest: /etc/containerd/certs.d/gcr.io/hosts.toml
    mode: "0644"
    content: |
      server = "https://gcr.io"

      [host."https://docker.m.daocloud.io"]
        capabilities = ["pull", "resolve"]
  notify: Restart containerd

- name: Configure ghcr.io mirror
  copy:
    dest: /etc/containerd/certs.d/ghcr.io/hosts.toml
    mode: "0644"
    content: |
      server = "https://ghcr.io"

      [host."https://docker.m.daocloud.io"]
        capabilities = ["pull", "resolve"]
  notify: Restart containerd

- name: Configure quay.io mirror
  copy:
    dest: /etc/containerd/certs.d/quay.io/hosts.toml
    mode: "0644"
    content: |
      server = "https://quay.io"

      [host."https://docker.m.daocloud.io"]
        capabilities = ["pull", "resolve"]
  notify: Restart containerd



- name: Configure crictl
  copy:
    dest: /etc/crictl.yaml
    content: |
      runtime-endpoint: unix:///var/run/containerd/containerd.sock
      image-endpoint: unix:///var/run/containerd/containerd.sock
      timeout: 10
      debug: false
    mode: "0644"

# journald

- name: Ensure journald drop-in directory exists
  file:
    path: /etc/systemd/journald.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure persistent journal dir exists
  file:
    path: /var/log/journal
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure journald log rotation
  copy:
    dest: /etc/systemd/journald.conf.d/99-k8s.conf
    content: |
      [Journal]
      Storage=persistent
      Compress=yes
      SystemMaxUse=1G
      SystemKeepFree=2G
      SystemMaxFileSize=100M
      MaxRetentionSec=30day
      MaxFileSec=7day
    mode: "0644"
  notify: Restart journald

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: true
    state: started

