apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influxdb
  namespace: prod-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: influxdb-nfs-prod
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-influxdb-prod