apiVersion: v1
kind: Service
metadata:
  name: influxdb-nodeport
  namespace: prod-basic
  labels:
    app: influxdb
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      nodePort: 30088