apiVersion: v1
kind: Service
metadata:
  name: influxdb-headless
  namespace: dev-basic
  labels:
    app: influxdb
spec:
  clusterIP: None
  selector:
    app: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: 8086