apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influxdb
  namespace: basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: influxdb-nfs-static
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-influxdb