apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minio-sit
  namespace: sit-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-nfs-sit
  resources:
    requests:
      storage: 500Gi
  volumeName: pv-minio-sit