apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
  namespace: sit-basic
  labels:
    app: minio
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30903
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30901