apiVersion: v1
kind: Service
metadata:
  name: klinx-itpm-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-itpm-server
  ports:
    - name: tcp-8716
      port: 8716
      protocol: TCP
      targetPort: 8716
