apiVersion: v1
kind: Service
metadata:
  name: klinx-imes-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-imes-server
  ports:
    - name: tcp-8736
      port: 8736
      protocol: TCP
      targetPort: 8736