apiVersion: v1
kind: Service
metadata:
  name: klinx-ismartbi-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-ismartbi-server
  ports:
    - name: tcp-8708
      port: 8708
      protocol: TCP
      targetPort: 8708