apiVersion: v1
kind: Service
metadata:
  name: klinx-icas-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-icas-server
  ports:
    - name: http-8701
      port: 8701
      protocol: TCP
      targetPort: 8701