apiVersion: v1
kind: Service
metadata:
  name: klinx-iomp-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-iomp-server
  ports:
    - name: http-8711
      port: 8711
      protocol: TCP
      targetPort: 8711
