apiVersion: v1
kind: Service
metadata:
  name: klinx-iqms-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-iqms-server
  ports:
    - name: http-8709
      port: 8709
      protocol: TCP
      targetPort: 8709