apiVersion: v1
kind: Service
metadata:
  name: klinx-bizbase-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-bizbase-server
  ports:
    - name: http-8751
      port: 8751
      protocol: TCP
      targetPort: 8751