apiVersion: v1
kind: Service
metadata:
  name: klinx-gateway-server
  namespace: saas
spec:
  type: NodePort
  selector:
    app: klinx-gateway-server
  ports:
    - name: http-8760
      port: 8760
      protocol: TCP
      targetPort: 8760
      nodePort: 30361