apiVersion: v1
kind: Service
metadata:
  name: klinx-datacollect-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-datacollect-server
  ports:
    - name: tcp-8702
      port: 8702
      protocol: TCP
      targetPort: 8702