apiVersion: v1
kind: Service
metadata:
  name: klinx-iccs-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-iccs-server
  ports:
    - name: tcp-8707
      port: 8707
      protocol: TCP
      targetPort: 8707