apiVersion: v1
kind: Service
metadata:
  name: klinx-iexpert-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-iexpert-server
  ports:
    - name: http-8717
      protocol: TCP
      port: 8717
      targetPort: 8717

