apiVersion: v1
kind: Service
metadata:
  name: klinx-idevicehub-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-idevicehub-server
  ports:
    - name: tcp-8710
      port: 8710
      protocol: TCP
      targetPort: 8710