apiVersion: v1
kind: Service
metadata:
  name: klinx-iaps-server
  namespace: saas
spec:
  type: ClusterIP
  selector:
    app: klinx-iaps-server
  ports:
    - name: tcp-8713
      port: 8713
      protocol: TCP
      targetPort: 8713