apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb-dev
  namespace: dev-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-nfs-dev
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-mongodb-dev