- name: Add kubernetes repo (Aliyun v1.34)
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://mirrors.aliyun.com/kubernetes-new/core/stable/v1.34/rpm/
      enabled=1
      gpgcheck=0
    mode: "0644"

- name: Make cache
  command: dnf makecache -y
  changed_when: false

- name: Install kubelet and kubeadm (all nodes)
  dnf:
    name:
      - "kubelet-{{ k8s_version }}"
      - "kubeadm-{{ k8s_version }}"
    state: present


- name: Install kubectl (masters only)
  dnf:
    name: "kubectl-{{ k8s_version }}"
    state: present
  when: "'masters' in group_names"


- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: true


- name: Pre-pull images (masters only)
  command: >
    kubeadm config images pull
    --kubernetes-version={{ k8s_version }}
    --image-repository={{ image_repo }}
  when: "'masters' in group_names"
  changed_when: false
  failed_when: false

