apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-admin
  namespace: paas-components
  labels:
    app: gw-admin
    version: private
spec:
  selector:
    matchLabels:
      app: gw-admin
      version: private
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gw-admin
        version: private
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7070"
    spec:
      containers:
        - name: gw-admin
          image: node5:443/ipaas-biz/gw-admin:private
          ports:
            - protocol: TCP
              containerPort: 7070
            - protocol: TCP
              containerPort: 8089
          envFrom:
            - configMapRef:
                name: paas-config
          env:
            - name: APP_MODE
              value: private
            - name: APP_VERSION
              value: private
          resources:
            requests:
              cpu: 300m
              memory: 1000Mi
            limits:
              cpu: 1000m
              memory: 2500Mi
      imagePullSecrets:
        - name: harbor-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gw-admin
  namespace: paas-components
  labels:
    app: gw-admin
    version: private
spec:
  sessionAffinity: None
  type: ClusterIP
  selector:
    app: gw-admin
  ports:
    - name: http-7070
      port: 7070
      protocol: TCP
      targetPort: 7070
    - name: http-8089
      port: 8089
      protocol: TCP
      targetPort: 8089