apiVersion: v1
kind: Namespace
metadata:
  name: paas-components
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paas-config
  namespace: paas-components
data:
  USER_NAME: "nacos"
  PASS_WORD: "itex@2023"
  NAMESPACE_ID: "a64c39ac-218e-4ad8-9fa3-298ce2989c9b"
  GROUP: "DEFAULT_GROUP"
  IP_ADDR: 'nacos-0.nacos-headless.basic.svc.cluster.local'
  PORT: '8848'


