apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: sit-basic
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379

    appendonly yes
    appendfsync everysec
    no-appendfsync-on-rewrite yes

    save ""

    maxmemory 1gb
    maxmemory-policy allkeys-lru

    tcp-keepalive 300
    timeout 0

    slowlog-log-slower-than 10000
    slowlog-max-len 128

    logfile ""
    loglevel notice

    dir /data