apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: sit-basic
  labels:
    app: redis
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 30379