apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influxdb-sit
  namespace: sit-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: influxdb-nfs-sit
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-influxdb-sit