- name: Check if already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: adminconf

- name: Render kubeadm.yaml
  template:
    src: kubeadm.yaml.j2
    dest: /root/kubeadm.yaml
    mode: "0644"
  when:
    - not adminconf.stat.exists
    - inventory_hostname == groups['masters'][0]

- name: kubeadm init
  command: kubeadm init --config=/root/kubeadm.yaml
  when:
    - not adminconf.stat.exists
    - inventory_hostname == groups['masters'][0]

- name: Setup kubectl for root
  shell: |
    mkdir -p /root/.kube
    cp -f /etc/kubernetes/admin.conf /root/.kube/config
  args:
    creates: /root/.kube/config
  when: inventory_hostname == groups['masters'][0]

- name: Upload certs and get certificate-key
  command: kubeadm init phase upload-certs --upload-certs
  register: upload_certs
  changed_when: false
  when: inventory_hostname == groups['masters'][0]

- name: Get join command
  command: kubeadm token create --print-join-command
  register: join_cmd
  changed_when: false
  when: inventory_hostname == groups['masters'][0]

- name: Save join info for other nodes
  add_host:
    name: k8s_cluster
    join_command: "{{ join_cmd.stdout }}"
    certificate_key: "{{ upload_certs.stdout_lines | last }}"
  when: inventory_hostname == groups['masters'][0]
