- name: Check if already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubeletconf

- name: Join as worker
  command: "{{ hostvars['172.16.15.51'].join_command_worker }}"
  when: not kubeletconf.stat.exists
