- name: Check if already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubeletconf

- name: Join worker
  command: "{{ hostvars['k8s_cluster'].join_command }}"
  when: not kubeletconf.stat.exists

