apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: sit-basic
data:
  my.cnf: |
    [mysqld]
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci

    default-authentication-plugin = mysql_native_password

    bind-address = 0.0.0.0
    skip-name-resolve = ON

    default-time-zone = '+08:00'

    max_connections = 1000

    innodb_file_per_table = 1
    innodb_flush_log_at_trx_commit = 1

    slow_query_log = 1
    slow_query_log_file = /var/lib/mysql/slow.log
    long_query_time = 2

    log_error_verbosity = 3

    [client]
    default-character-set = utf8mb4

    [mysql]
    default-character-set = utf8mb4