apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-sit
  namespace: sit-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-nfs-sit
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-mysql-sit