apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
  namespace: sit-basic
  labels:
    app: mongodb
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      nodePort: 30017