apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb-sit
  namespace: sit-basic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-nfs-sit
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-mongodb-sit