[masters]
master1 ansible_host=172.16.15.51
master2 ansible_host=172.16.15.52
master3 ansible_host=172.16.15.53

[nodes]
node1 ansible_host=172.16.15.54
node2 ansible_host=172.16.15.55
node3 ansible_host=172.16.15.56

[lb_master]
master1

[lb_backup]
master2

[all:vars]
ansible_user=root
ansible_port=22
