[masters]
master1 ansible_host=172.16.15.61
master2 ansible_host=172.16.15.62
master3 ansible_host=172.16.15.63

[nodes]
node1 ansible_host=172.16.15.64
node2 ansible_host=172.16.15.65
node3 ansible_host=172.16.15.66

[lb_master]
master1

[lb_backup]
master2

[all:vars]
ansible_user=root
ansible_port=22
